added tests against build configuration creation
GolubtsovMaxim/Workshop pull request #10
Opened 2024-11-03 22:00 UTC by GolubtsovMaxim

Tests are in CreateBuildConfigurationTest class

2024-11-10 22:23 UTC, nobugs-me requested changes
Привет! 

Спасибо за выполнение базового ДЗ! ⚡️

Тест выполнен корректно, но не хватает проверки, что сущность не создалась в негативном тесте. 

Добавь, пожалуйста, и будет Approve 🤝

2024-11-10 22:23 UTC, nobugs-me commented on main/src/test/kotlin/ui/CreateBuildConfigurationTest.kt
> +        CreateProjectPage.open("_Root")
В Котлине для Page Object ты можешь использовать свой кастомный KotlinDSL 

Тогда тест будет в формате 

```
uiTest {
    loginAs(user)
    
    projectPage {
         createForm(REPO_|URL) 
         setupProject(projectName, buildTypeName)
    }
}
```

2024-11-10 22:23 UTC, nobugs-me commented on main/src/test/kotlin/ui/CreateBuildConfigurationTest.kt
> +        softy.assertTrue(element.text == buildConfigurationName)
Не хватает проверки на уровне API, что сущность создалась.

2024-11-10 22:23 UTC, nobugs-me commented on main/src/test/kotlin/ui/CreateBuildConfigurationTest.kt
> +        softy.assertTrue(elements.isEmpty)
Не хватает проверки на уровне API, что сущность не создалась.

2024-11-15 22:26 UTC, GolubtsovMaxim commented
Саша, я случайно в идее удалил одну из проблем :(
Там было что-то про использование Kotlin DSL

2024-11-23 14:56 UTC, merged

2024-11-23 21:52 UTC, nobugs-me commented
Теперь зачтено 

> Саша, я случайно в идее удалил одну из проблем :( Там было что-то про использование Kotlin DSL

Я писала, что ты в Котлин можешь писать Page Object как Kotlin DSL, тогда у тебя получится совсем нативное использование типо: 

```
buildPage { 
      createBuild(buildName="")
}
```

2024-11-23 21:53 UTC, nobugs-me commented
Отлично теперь зачтено ⚡️