added tests against Project
GolubtsovMaxim/Workshop pull request #9
Opened 2024-10-08 20:04 UTC by GolubtsovMaxim

2024-10-12 15:29 UTC, nobugs-me requested changes
Привет! 

Спасибо за выполнение базового ДЗ! ⚡️

Тест выполнен корректно, но есть комменты, которые нужно исправить и после исправления будет Approve 🤝

2024-10-12 15:29 UTC, nobugs-me commented on main/src/test/kotlin/ProjectTest.kt
> +            .statusCode(HttpStatus.SC_BAD_REQUEST)
Во всех случаях нужны также проверки самого сообщения - в нем должно объяснятся, что пошло не так.

2024-10-13 13:19 UTC, GolubtsovMaxim commented on main/src/test/kotlin/ProjectTest.kt
> +            .statusCode(HttpStatus.SC_BAD_REQUEST)
Добавил проверки сообщения (надеюсь понял правильно что от меня требовалось) @nobugs-me

2024-10-14 13:11 UTC, nobugs-me approved these changes

2024-10-14 13:11 UTC, nobugs-me commented on main/src/test/kotlin/ProjectTest.kt
> +            .statusCode(HttpStatus.SC_BAD_REQUEST)
Да, спасибо!

2024-10-23 20:36 UTC, merged